name: gps001
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  location: ^7.0.0
  logger: ^2.4.0
  fluttertoast: ^8.2.6 
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  url_launcher: ^6.3.0
  provider: ^6.0.1
  flutter_spinkit: ^5.2.1
  http: ^1.2.2
  flutter_map_cancellable_tile_provider: ^3.0.0
  flutter_map_math: ^0.1.7
  prompt_dialog: ^1.0.16 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets: 
    - assets/images/geo/
